name: vidar
description: "Private Communications Application"
publish_to: "none"
version: 1.2.1-beta+4
repository: "https://github.com/DrSolidDevil/Vidar"
issue_tracker: "https://github.com/DrSolidDevil/Vidar/issues"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  flutter_secure_storage: ^9.2.4
  logging: ^1.3.0
  uuid: ^4.5.1
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0

flutter:
  uses-material-design: true
