name: vidar
description: "Private Communications Apllication"
publish_to: "none"
version: 0.2.0
repository: "https://github.com/DrSolidDevil/Vidar"
issue_tracker: "https://github.com/DrSolidDevil/Vidar/issues"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
