name: vidar
description: "Private Communications Apllication"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
